[package]
authors = ["PureStake"]
edition = "2018"
name = "pallet-crowdloan-rewards"
version = '0.6.0'
description = "Reward citizens who participated in a crowdloan to acquire a parachain slot o nthe backing relay chain."

[dependencies]
parity-scale-codec = { version = "2.1.1", default-features = false}
serde = { version = "1.0.101", optional = true, features = ["derive"], default-features = false }
log = { version = "0.4", default-features = false }
scale-info = { version = "1.0", default-features = false, features = ["derive"] }

frame-support = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
frame-system = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
sp-core = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
sp-runtime = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
sp-std = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
sp-io = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
pallet-balances = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
pallet-utility = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false }
frame-benchmarking = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false, optional = true }
ed25519-dalek = { version = "1.0.1", default-features = false, features = ["u64_backend", "alloc"], optional = true }
sp-trie = { git = "https://github.com/mangata-finance/substrate", branch = "mangata-dev", default-features = false, optional = true }
mangata-primitives = { git = "https://github.com/mangata-finance/mangata-node", branch = "develop", default-features = false }
orml-tokens = { default-features = false, version = '0.4.1-dev', git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }

[dev-dependencies]
orml-traits = { default-features = false, version = "0.4.1-dev", git = "https://github.com/mangata-finance/open-runtime-module-library", branch = "mangata-dev" }

[features]
default = ["std"]
std = [
    "pallet-balances/std",
    "parity-scale-codec/std",
    "pallet-utility/std",
    "frame-benchmarking/std",
    "frame-support/std",
    "frame-system/std",
    "sp-core/std",
    "sp-runtime/std",
    "serde",
    "log/std",
    "sp-std/std",
    "sp-io/std",
    "scale-info/std",
    "mangata-primitives/std",
    "orml-tokens/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "sp-trie",
    "ed25519-dalek",
]

[patch."https://github.com/mangata-finance/open-runtime-module-library"]
orml-tokens = { git = "https://github.com/mangata-finance//open-runtime-module-library", branch = "mangata-dev" }
orml-traits = { git = "https://github.com/mangata-finance//open-runtime-module-library", branch = "mangata-dev" }
